apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-nginx
  namespace: tests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flux-nginx
  template:
    metadata:
      labels:
        app: flux-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
