apiVersion: v1
kind: Service
metadata:
  name: flux-nginx-service
  namespace: tests
spec:
  type: NodePort
  selector:
    app: flux-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
